config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :items
  resources :orders
  resources :accounts
  devise_for :users, controllers: {omniauth_callbacks: "callbacks"}

  root 'users#home'


  get "/account/:id/payment", to: "accounts#payment", as: "user_payment"
  post "/account/:id/payment", to: "accounts#create_payment", as: "user_create_payment"
  get "/account/:id/pallets", to: "accounts#pallets", as: "user_pallets"
  post "/account/:id/pallets", to: "accounts#return_pallets", as: "user_return_pallets"

  get "/books", to: "accounts#books", as: "books"

  get "/account/:id/orders", to: "accounts#orders", as: "user_account"     #regular action


  get "/books/orders", to: "accounts#books_orders", as: "books_orders"
  post "/notes", to: "notes#api_create"#, as: "notes"
  get "/api/next_note/:accid/:noteid", to: "notes#api_show_next"
  get "/api/previous_note/:accid/:noteid", to: "notes#api_show_previous"

  #get "/api/account/:id", to: "accounts#api_account"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauth_providers => [:facebook]

  has_one :account
  has_many :orders, through: :account

  validates :name, :presence => {:message => "-please include your name!"}

  enum role: [:admin, :normal]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email || 'no_omniauth_email_provided@dummy.com'
      user.password = Devise.friendly_token[0,20]
      user.save
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    @item = Item.new
    @account = Account.new
  end
end

app/views/users/home.html.erb
<% if current_user.try(:admin?) %>
  <h3 style='color: red; text-decoration: underline'> ADMIN CONSOLE </h3>
<% end %>
<h1> Hello, welcome to Williams Soils and Sod! </h1><br>

<%= link_to "Sign In", new_user_session_path unless current_user %><br>
<%= link_to "Sign Up", new_user_registration_path unless current_user %><br><br>

<%#= link_to "Create Order", new_account_order_path unless !current_user%><br>
<%= link_to "Create Order", new_order_path unless !current_user%><br>
<%= link_to "View Account", user_account_path(current_user) unless !current_user || current_user.admin? %><br>

<% if policy(@item).index? %>
  <%= link_to "View/Edit/Create Items", items_path %>
<% end %><br><br>

<% if policy(@account).index? %>
  <%= link_to "View Accounts", accounts_path %>
<% end %><br><br>

<% if policy(@account).books? %>
  <%= link_to "View Books", books_path %>
<% end %><br><br><br>

<% if current_user %>
  <b><%= "Signed in as " + current_user.name %><br></b>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
<% end %>