config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :items
  resources :orders
  resources :accounts
  devise_for :users, controllers: {omniauth_callbacks: "callbacks"}

  root 'users#home'


  get "/account/:id/payment", to: "accounts#payment", as: "user_payment"
  post "/account/:id/payment", to: "accounts#create_payment", as: "user_create_payment"
  get "/account/:id/pallets", to: "accounts#pallets", as: "user_pallets"
  post "/account/:id/pallets", to: "accounts#return_pallets", as: "user_return_pallets"

  get "/books", to: "accounts#books", as: "books"

  get "/account/:id/orders", to: "accounts#orders", as: "user_account"     #regular action


  get "/books/orders", to: "accounts#books_orders", as: "books_orders"
  post "/notes", to: "notes#api_create"#, as: "notes"
  get "/api/next_note/:accid/:noteid", to: "notes#api_show_next"
  get "/api/previous_note/:accid/:noteid", to: "notes#api_show_previous"

  #get "/api/account/:id", to: "accounts#api_account"
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items

  validates_format_of :item_type, :with => /\A[A-Za-z\s]*\z/, :message => "input is invalid. No numbers or special characters.."

  #scope :item_total, ->(item) { where('account_id = ?', account)}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(params_check)
    if @item.save
      redirect_to items_path
    else
      render :partial => 'items/item_form', locals: {item: @item}
    end
  end

  def index
    @items = Item.all
    authorize @items
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params_check)
      redirect_to items_path
    else
      render :partial => 'items/item_form', locals: {item: @item}
    end
  end

  private

  def params_check
    params.require(:item).permit(:item_type, :price, :with_pallet)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def includes_pallet(item)
    if item.with_pallet
      'Yes'
    else
      'No'
    end
  end
end

app/views/items/_item_form.html.erb
<style>
.field_with_errors {
  border: 3px solid red;
  display: inline;
}
</style>

<% item.errors.full_messages.each do |msg| %>
  <%= msg %>
<% end %>
<br><br>

<%= form_for item do |f| %>
  <%= f.label "Item type: " %>
  <%= f.text_field :item_type %><br><br>
  <%= f.label "Price: $" %>
  <%= f.text_field :price %><br><br>
  <%= f.label "Includes pallet?" %>
  <%= f.check_box :with_pallet %><br><br>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<%= render :partial => 'items/item_form', locals: {item: @item} %>

app/views/items/index.html.erb
<%= link_to "Create New Item", new_item_path %><br>
<h2>Items: </h2>
<% @items.each do |item| %>
  <b>Item Type: </b><%= item.item_type %><br>
  <b>Price: </b><%= item.price %><br>
  <b>Includes Pallet: </b><%= includes_pallet(item) %><br>
  <%= link_to "Edit Item", edit_item_path(item) %><br>
  ------------------------------------<br>
<% end %>

app/views/items/new.html.erb
<%= render :partial => 'items/item_form', locals: {item: @item} %>