config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :items
  resources :orders
  resources :accounts
  devise_for :users, controllers: {omniauth_callbacks: "callbacks"}

  root 'users#home'


  get "/account/:id/payment", to: "accounts#payment", as: "user_payment"
  post "/account/:id/payment", to: "accounts#create_payment", as: "user_create_payment"
  get "/account/:id/pallets", to: "accounts#pallets", as: "user_pallets"
  post "/account/:id/pallets", to: "accounts#return_pallets", as: "user_return_pallets"

  get "/books", to: "accounts#books", as: "books"

  get "/account/:id/orders", to: "accounts#orders", as: "user_account"     #regular action


  get "/books/orders", to: "accounts#books_orders", as: "books_orders"
  post "/notes", to: "notes#api_create"#, as: "notes"
  get "/api/next_note/:accid/:noteid", to: "notes#api_show_next"
  get "/api/previous_note/:accid/:noteid", to: "notes#api_show_previous"

  #get "/api/account/:id", to: "accounts#api_account"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :notes
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :find_account
  include AccountsHelper

  def index
    @accounts = Account.all
    authorize @accounts
  end

  def orders
    @note = Note.new
    @current_note = @account.notes.last
    @orders = @account.orders
    authorize @account
  end

  def payment
    authorize @account
  end

  def create_payment
    payment = BigDecimal.new(params[:debit])
    make_payment(@account, payment)

    redirect_to user_account_path(@account.user_id)
  end

  def pallets
  end

  def return_pallets
    amount = params[:return_amt].to_i
    pallet_return(@account, amount)

    redirect_to user_account_path(@account.user_id)
  end

  def books
    @items = Item.all
    @book_printout_array = item_setter(@items)
  end

  def books_orders
    @accounts = Account.all
    @orders = Order.all
    render json: @orders
  end

  private

  def item_setter(items)
    current_book = []
    items.each do |item|
      current_book << "#{item.item_type}: " + OrderItem.item_totals(item).to_s
    end
    return current_book
  end

  def find_account
    @account = Account.find_by(:user_id => params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def current_balance(balance)
    sprintf("%.2f", balance.truncate(2))
  end

  def order_total(order)
    total = 0
    tax = 1.06
    pallet_price = 6.00
    order.order_items.each do |order_item|
      if order_item.pallet_count > 0
        total += ((order_item.quantity * order_item.item.price) * tax) + (order_item.pallet_count * pallet_price)
      else
        total += (order_item.quantity * order_item.item.price * tax)
      end
    end
    number_to_currency(total)
  end

  def pallet_total(order)
    total = 0
    order.order_items.each do |order_item|
      total += order_item.pallet_count
    end
    total
  end

  def pallet_return(account, amount)
    account.pallet_count -= amount
    account.balance -= amount * 6
    account.save
  end

  def make_payment(account, payment)
    account.balance -= payment
    account.save
  end

  def order_date(date)
    date_obj = Time.parse(date)
    date_obj.strftime('%D, %l:%M %p')
  end

  def note_date(date)
    date_obj = Time.parse(date.to_s)
    date_obj.strftime("%m/%d/%Y").gsub(/\b0(?=\d)/, '')
  end

  def init_current_note_builder(current_note)
    current_note.content + ' @ date: ' +  note_date(current_note.created_at)
  end

  def account_details(account)
    content_tag(:h4, "Name: " + account.user.name + " | " + "Email: " + account.user.email) unless !account.user.email
  end
end

app/views/accounts/_orders_list.erb
<h4>Order placed: <%= order_date(order.date) %></h4>

<% order.order_items.each do |order_item| %>
  <li style="padding-left:19px">
    <%= order_item.item.item_type %>, Quantity: <%= order_item.quantity %><br>
  </li>
<% end %>

<p style="color:green">Total: <%= order_total(order) %></p>
<p style="color:brown">Pallets: <%= pallet_total(order) %></p>

app/views/accounts/books.html.erb
<h3>Company Books</h3>
<h4 style='color: red; text-decoration: underline'>Mechandise sold count:</h4>
<% @book_printout_array.each do |item| %>
  <b><%= item %></b><br>
<% end %>
<br><br><br>

<div id="orders"></div>

<button class="js-orders">VIEW ALL ORDERS</button>

app/views/accounts/index.html.erb
<% @accounts.each do |account| %>
  <b><%= account.user.name %> | CURRENT BALANCE: $<%= current_balance(account.balance) %></b><br>
  <%= link_to "Account Details", user_account_path(account.user) %> |
  <%= link_to "Make Payment", user_payment_path(account.user) %> |
  <%= link_to "Return Pallets", user_pallets_path(account.user) %><br><br>
<% end %>

app/views/accounts/orders.html.erb
<h1> Account Details </h1>

<%= render partial: 'accounts/orders_list', collection: @orders, as: :order %>
<br>
<h2 style="color:red">CURRENT BALANCE: $<%= current_balance(@account.balance) %></h2>
<h3 style="color:brown">PALLETS OUT: <%= @account.pallet_count %></h3>
<%= account_details(@account) %>

<br>
<h1> NOTES: </h1>
<span class='js-previous-note-div'><button class='js-previous-note-button'><</button></span>
<span id="show-note">
  <% if @current_note %>
    <%= content_tag(:span, init_current_note_builder(@current_note) , :class => 'js-current-note', :'data-note-id' => @current_note.id, :'data-account-id' => @current_note.account_id) %>
  <% end %>
</span>
<span class='js-next-note-div'><button class='js-next-note-button'>></button></span>

<br>

<div class='show-error'>

</div>

<% if policy(@note).api_create? %>
  <%= form_for @note, :html=> {:class => 'js-new-note'} do |f| %>
    <%= f.hidden_field :account_id, :value => @account.id %>
    <%= f.text_field :content %>
    <%= f.button 'create new note' %>
  <% end %>
<% end %>

app/views/accounts/pallets.html.erb
Pallets Out: <%= @account.pallet_count %>
<%= form_tag user_return_pallets_path do %>
  <%= number_field_tag :return_amt %>
  <%= submit_tag "Return pallets"%>
<% end %>

app/views/accounts/payment.html.erb
Balance Due: $<%= sprintf("%.2f", @account.balance.truncate(2)) %>

<%= form_tag user_create_payment_path do %>
  <%= number_field_tag(:debit, nil, step: :any, :placeholder => "payment amount") %>
  <%= submit_tag "Submit payment" %>
<% end %>